version: "3.9"

services:
  db:
    image: postgres:15
    container_name: drf_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

#  test-db:
#    image: postgres:15
#    container_name: test_database
#    environment:
#      POSTGRES_DB: "test"
#      POSTGRES_USER: "testuser"
#      POSTGRES_PASSWORD: "testpassword"
#    volumes:
#      - postgres_test_data:/var/lib/postgresql/data
#    ports:
#      - "5430:5432"

  backend:
    build: .
    container_name: drf_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
#      - redis
    env_file:
      - .env

#  redis:
#    image: redis:6.2
#    container_name: redis
#    ports:
#      - "6379:6379"
#    command: "redis-server --appendonly yes"

#  celery_worker:
#    build: .
#    command: celery -A core worker --loglevel=info
#    volumes:
#      - .:/app
#    env_file:
#      - .env
#    depends_on:
#      - redis
#      - db

#  mailhog:
#    image: mailhog/mailhog
#    container_name: mailhog
#    platform: linux/amd64
#    ports:
#      - "8025:8025" # Web interface for viewing emails
#      - "1025:1025" # SMTP server for capturing outgoing emails

volumes:
  postgres_data: